version: '3'
services:
  portfolio-app:
    container_name: portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
       - .:/app
       - /app/node_modules
